apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhoas-operator.openshift-operators: ""
  name: rhoas-operator
spec:
  channel: beta
  installPlanApproval: Automatic
  name: rhoas-operator
  source: rhoas-operators2
  sourceNamespace: openshift-marketplace
  startingCSV: rhoas-operator.0.6.5
  config:
    resources:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m"
